name: sandbox
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - ipykernel
  - numpy=1.24.3
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - graphviz
  - pip:
      - tensorflow==2.14.0
      - tensorflow-probability==0.22.0
      - tf-keras
      - imbalanced-learn
      - pymc==5.10.3
      - causalpy
      - typing-extensions==4.5.0
